name: gamegame1666_3proxy

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка программ.
      run: |
        Invoke-WebRequest https://github.com/gamegame1236/3proxy-config/raw/main/3proxy.zip -OutFile "3proxy.zip"
    - name: Загрузка 3proxy файла.
      run: |
        Expand-Archive 3proxy.zip 
    - name: Подключение к учётной записи 3proxy.
      run: |
        cd 3proxy
        cd 3proxy
        cd bin64
        .\3proxy.exe
    - name: Включение доступа 3proxy.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Сделано успешно! Вы можете закрыть вкладку.
      run: cmd /c loop.bat
